### ISSUE TITLE
Unresolved symbol in Visual Studio 2017 C++ program when using SHA3

### ISSUE THREAD

**Issue by ikonuk** [calccrypto/Hashes#1]
I was able to compile SHA3 and all associated files. I could even build if I do not instantiate a class. However, when I instantiate an object in C++ main as follows:

SHA3 <128> mysha3;
mysha3.update(myuuid);   // myuuid is std::string
std::cout << " SHA3 Key = " << mysha3.digest() << std::endl;

I get an unresolved symbol error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall SHA3<128>::digest(void)" (?digest@?$SHA3@$0IA@@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	biosuuid	E:\AArea\ik20a\Comp\HardwareInfo\bios_uuid\getbiosuuid2\main.obj	1	

Thank you for any help.

I. Konuk

**Comment by calccrypto** [comment]
This sounds like you did not link properly. Are you sure the library file was linked properly? Do the other hashes work?

**Comment by ikonuk** [comment]
I believe there is no separate library file. The code given is self contained.

It appears to me like I am not instantiating the SHA3 class properly. It is defined as class template. Honestly this C++ code is too smart and complex for me to understand fully. 

In fact, the linker seems to be indicating missing a form of SHA3 symbol:

"public: __thiscall SHA3<128>::SHA3<128>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)"

**Comment by calccrypto** [comment]
I think I figured it out. SHA 3 (not Keccak) is only defined for 224, 256, 384, and 512 bit digests, so using the template, I only defined those [here](https://github.com/calccrypto/Hashes/blob/master/Hashes/SHA3.cpp#L180), but did not make it explicit in the header. Those lines define the concrete classes for SHA3<224, 256, 384, and 512>, but not 128 which is why you are getting undefined references. If you want to use SHA3<128>, you have to go through Keccak.

I will review the SHA3 code this weekend.

**Comment by ikonuk** [comment]
Thank you very much indeed.

**Comment by calccrypto** [comment]
Would you rather I allow for arbitrary lengths, or explicitly prevent lengths other than 224, 256, 384, or 512 from being compiled at all?

**Comment by ikonuk** [comment]
Thank you for generous offer. What you have provided has more than satisfied my need for the time being, but if it is not much time I could use an arbitrary length version.

By the way, I am truly impressed with your neat and tight C++ code. I have never seen a const non-type being used like you do in a C++ template. I know now why you have used it. In addition, I am still struggling to understand  how (cleverly) you used dependent names in a template (I am referring to "<d>::" in statements like:

typename SHA3 <d>::StateArray SHA3 <d>::
SHA3 <d>::StateArray Aprime = A;

Not only your code has solved a practical problem for me, but it provided me the best training in C++ templates I needed for long time. Would you recommend me some reading or resource to digest the topic better?

Thank you again very much.  With kindest regards.

**Comment by ikonuk** [comment]
I meant to type "<d>::"

**Comment by ikonuk** [comment]
`<d>::`

**Comment by calccrypto** [comment]
[SHA3 now allows for any digest size that is a multiple of 8 bits](https://github.com/calccrypto/Hashes/commit/56cc1f349d2cd08fa40497d17cc946c28619012c). Please let me know if something isnt working right.

**Comment by calccrypto** [comment]
> Would you recommend me some reading or resource to digest the topic better?

I recommend writing actual code. When I hit something that I do not know how to do, I search for similar ideas online and usually end up on StackOverflow or https://en.cppreference.com/, and try to map the results to my problem. This allows me to internalize the solution, since it is no longer a bunch of abstract ideas that I will never use - it becomes a solution to a problem I am familiar with.

**Comment by ikonuk** [comment]
Thank you for generous offer. What you have provided has more than satisfied my need, but if it is not much time I could use an arbitrary length version.

By the way, I am truly impressed with your neat and tight C++ code. I have never seen a const non-type being used like you do. In addition, I am still struggling to understand  how (cleverly) you used dependent names in a template (I am referring to <

**Comment by ikonuk** [comment]
Thnak you again very much. I tried to compile the new version of sha3. Both Visual Studio 2017 and 2019 gave compilation errors C2760 and C7510 in lines 7,30,54,65,84 indicating a typedef is required. I inserted typedef like:

`typename SHA3 <d, Valid>::StateArray A = {{0}};`

on line 7. However, I started getting missing symbol errors LNK2001 like:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl hexlify(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?hexlify@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@_N@Z)	biosuuid	E:\AArea\ik20a\Comp\HardwareInfo\bios_uuid\getbiosuuid3\main.obj	1	
`

and 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl little_end(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int const &)" (?little_end@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV12@ABI@Z)	biosuuid	E:\AArea\ik20a\Comp\HardwareInfo\bios_uuid\getbiosuuid3\main.obj	1	
`

I tried to include my own name space like in this example:

https://stackoverflow.com/questions/44774036/why-use-a-tpp-file-when-implementing-templated-functions-and-classes-defined-i


It did not help.

**Comment by calccrypto** [comment]
Did you compile and link [includes.cpp](https://github.com/calccrypto/Hashes/blob/master/common/includes.cpp)?

**Comment by calccrypto** [comment]
What did you mean by self contained? Did you only compile `SHA3.cpp` (before it got moved)? What about the rest of the files?

**Comment by ikonuk** [comment]
These are the include files in front of the new sha3.h:

`#include <array>
#include <type_traits>

#include "cryptomath.h"
#include "includes.h"
#include "HashAlg.h"

#include "KECCAK_Const.h"`
```

No, I did not include old sha3.cpp. Just the new sha3.tpp. I tried placing it both in the header and source sections.

I am not missing anything, I think, because it is compiling with the modifications I listed. Linker is giving the missing symbol error.

**Comment by calccrypto** [comment]
include != link. You need to convert includes.cpp into binary and link your executable with it so that it knows what `hexlify` and `little_end` are. Right now, the compiler simply knows that they exist, without knowing how they are implemented.

**Comment by ikonuk** [comment]
I apologize. It was all my mistake. When I did the first project, I combined all cpp files (I know it is a terrible practice. When I deleted sha3.cpp, I lost includes.cpp and HashAlg.cpp implementations.

I tried 256, 88, 104 at the same time. It is working perfectly. I would like to express my gratitude and I apologize again. You may close this case if you wish now. THANK YOU!
